//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncLab.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINSIGND
    {
        public string SIGNID { get; set; }
        public int ROWSEQ { get; set; }
        public int COLSEQ { get; set; }
        public string NUM { get; set; }
        public string ISBINGO { get; set; }
        public Nullable<decimal> SIGNRATEO { get; set; }
    
        public virtual BINSIGNM BINSIGNM { get; set; }
    }
}
