//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncLab.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINSIGNB
    {
        public string SIGNID { get; set; }
        public string KINDNO { get; set; }
        public Nullable<decimal> BONUSMONEY2 { get; set; }
        public Nullable<decimal> BONUSMONEY3 { get; set; }
        public Nullable<decimal> BONUSMONEY4 { get; set; }
        public Nullable<decimal> BONUSMONEYO { get; set; }
        public Nullable<decimal> SIGN2 { get; set; }
        public Nullable<decimal> SIGN3 { get; set; }
        public Nullable<decimal> SIGN4 { get; set; }
        public Nullable<decimal> SIGNO { get; set; }
        public Nullable<decimal> SIGNMONEY2 { get; set; }
        public Nullable<decimal> SIGNMONEY3 { get; set; }
        public Nullable<decimal> SIGNMONEY4 { get; set; }
        public Nullable<decimal> SIGNMONEYO { get; set; }
        public Nullable<decimal> BIN2 { get; set; }
        public Nullable<decimal> BIN3 { get; set; }
        public Nullable<decimal> BIN4 { get; set; }
        public Nullable<decimal> BINO { get; set; }
        public string BINNUM2 { get; set; }
        public string BINNUM3 { get; set; }
        public string BINNUM4 { get; set; }
        public string BINNUMO { get; set; }
        public Nullable<decimal> SIGNRATE2 { get; set; }
        public Nullable<decimal> SIGNRATE3 { get; set; }
        public Nullable<decimal> SIGNRATE4 { get; set; }
    
        public virtual BINSIGNM BINSIGNM { get; set; }
    }
}
