//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncLab.WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnderBingoEntities : DbContext
    {
        public UnderBingoEntities()
            : base("name=UnderBingoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BINSIGND> BINSIGNDs { get; set; }
        public virtual DbSet<BINSIGNM> BINSIGNMs { get; set; }
        public virtual DbSet<BINSIGNB> BINSIGNBs { get; set; }
    }
}
